export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="lichao"

plugins=(alias-finder autojump copypath copyfile command-not-found
         colored-man-pages fzf git gitfast poetry taskwarrior
         zsh-vi-mode zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

export LC_ALL=en_US.UTF-8

. $HOME/.asdf/asdf.sh
eval "$(direnv hook zsh)"

show_virtual_env() {
  if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
    echo "($(basename $VIRTUAL_ENV)) "
  fi
}
PS1='$(show_virtual_env)'$PS1

# Hook for desk activation
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true

alias vi="python $HOME/.config/nvim/vi_lua_conf.py"
alias vio="python $HOME/.config/nvim/vi_vam.py"


# zsh-vi-mode config:
zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

