SHELL := zsh

pypath := ~/.local/opt/python-3.10.12/
sspath := ~/warez/starship
dotfiles_repo := git@github.com\:leetschau/my-dotfiles.git
pipx_path := ~/.local/pipx/
pppath := ~/.local/share/nvim/site/pack/paqs
nvimpath := https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz

PYTAR := python.tgz
PYROOT := $(shell dirname $(pypath))
DTFILES := mydotfiles
PYAPPS := pipx_apps.tgz
PYAPP_ROOT := $(shell dirname $(pipx_path))
PAQTAR := paq_plugins.tgz
PAQROOT := $(shell dirname $(pppath))
DATADIR := data
DFILE := data.tgz
VIMTAR := $(shell basename $(nvimpath))

USERNAME = leo

python: $(pypath)
	tar czf $(PYTAR) -C $(PYROOT) $(shell basename $(pypath))

dotfiles:
	git clone $(dotfiles_repo) $(DTFILES)

pipx-apps: $(pipx_path)
	tar czf $(PYAPPS) -C $(PYAPP_ROOT) $(shell basename $(pipx_path))

neovim:
	wget $(nvimpath)

paq_plugins: $(pppath)
	tar czf $(PAQTAR) -C $(PAQROOT) $(shell basename $(pppath))

build: python $(sspath) dotfiles pipx-apps neovim paq_plugins
	mkdir $(DATADIR)
	mv *.tgz *.tar.gz $(DTFILES) $(DATADIR)
	cp $(sspath) $(DATADIR)
	tar czf $(DFILE) $(DATADIR)
	rm -rf $(DATADIR)

clean:
	rm -rf $(DATADIR)
	rm -rf $(DTFILES)

install-sys-apps-ubuntu:
	apt install -y silversearcher-ag autojump fd-find fish fzf tree

install-sys-apps-archlinux:
	pacman -S base-devel fd fish git git-delta openssh the_silver_searcher tree

install-sys-apps-alpine:
	lxc exec ica -- apk add sudo shadow git fish python3 delta the_silver_searcher neovim starship pipx fzf

user:
	useradd -m -s /bin/fish $(USERNAME)
	usermod -aG sudo $(USERNAME)
	passwd $(USERNAME)

deploy: $(DFILE) install-sys-apps-ubuntu user
	cp $(DFILE) ~$(USERNAME)/
	su - $(USERNAME)
	mkdir -p ~/warez ~/.local/bin $(PYROOT) $(PAQROOT)
	cd ~/warez
	tar xf ~/$(DFILE)
	cd ~/warez/$(DATADIR)
	sudo cp starship /usr/local/bin/
	tar xf $(PYTAR) -C $(PYROOT)
	tar xf $(VIMTAR) -C $(PYROOT)
	tar xf $(PYAPPS) -C $(PYAPP_ROOT)
	tar xf $(PAQROOT) -C $(PAQROOT)
	cd $(DTFILES)
	/home/leo/.local/pipx/venvs/dotdrop/bin/dotdrop install -p headless
	cd ~/.local/bin
	ln -s ~/.local/opt/nvim-linux64/bin/nvim nvim

