[directory]
truncation_length = 8
truncation_symbol = "…/"

[conda]
format = "[$symbol$environment](dimmed purple) "

[custom.pip]
command = "echo PIP:TUNA"
when = "set -q PIP_INDEX_URL"
style = "dimmed yellow"
